### PR TITLE
fix: add rednoseday footer and socia link, fix #61

### LINKED ISSUE #61: Add Red Nose Day footer + social link
API isn't ready so fallback to fetch comicrelief.com footer menu instead

### PR DESCRIPTION
**Pull request by KoalaMango**

### CODE REVIEW

File: src/stories/index.js [hunk 1]
```diff
@@ -45,6 +45,14 @@ storiesOf('Footer', module)
       const campaign = 'sportrelief';
       return (<Footer copy={copy} source={source} campaign={campaign} />);
     }),
+  )
+  .add('Red Nose Day',
+    withInfo('rednoseday.com footer')(() => {
+      const copy = text('Copy', 'copyright 2018');
+      const source = 'https://www.comicrelief.com'; // fallback to comicrelief.com
+      const campaign = 'rednoseday';
```
Comment (AndyEPhipps) [inline src/stories/index.js]: Do we need to use this text function on each of the const vars here too? Not 100% sure what it's actually doing, though

Comment (KoalaMango) [reply src/stories/index.js]: We need to pass value to props but don't need repeat const ;)  I only copied entire block from previous ones. Agree we can definitely tidy them up :)

**Comment by twhiteley** [comment]
➤ Tom Whiteley commented:

Transition made by Unito
